### PR TITLE
fix for NUTCH-2438 contributed by tmzzngl

### PR DESCRIPTION
**Pull request by tulay**
Ran generate-gora-src task but it didn't change the WebPage.java file.

### CODE REVIEW

**Comment by tulay** [comment]
DB | Test Result
------------ | -------------
MongoDB 3.4.9 | OK

**Comment by lewismc** [comment]
Ideally we want checks against the following

DB | Test Result
------------ | -------------
Apache Avro 1.8.1 |
Apache Hadoop 2.5.2 |
Apache HBase 1.2.3 |
Apache Cassandra 3.11.0 (Datastax Java Driver 3.3.0) |
Apache Solr 6.5.1 |
MongoDB 3.4.9 | OK
Apache Accumlo 1.7.1 |
Apache Spark 1.4.1 |
Apache CouchDB 1.4.2 (test containers 1.1.0) |
Amazon DynamoDB (driver) 1.10.55 |
Infinispan 7.2.5.Final |
JCache 1.0.0 with Hazelcast 3.6.4 support. |
OrientDB 2.2.22 |
Aerospike 4.0.6 |

**Comment by tulay** [comment]
I'll try to do couple of more with docker containers.

**Comment by lewismc** [comment]
I'll also post over on user@ and dev@gora that we are looking for test volunteers. Thanks.

**Comment by lewismc** [comment]
Superseded by #258 thank you @tulay for the work so far

**Pull request closed without merging**
