### PR TITLE
NUTCH-2171 Nutch upgrade to Java 1.8

### PR DESCRIPTION
**Pull request by kamaci**

### CODE REVIEW

**Comment by lewismc** [comment]
This is great @kamaci I've pulled this locally, all compiles and tests fine. Any objections to merging into master?

**Comment by kamaci** [comment]
@lewismc you can merge it into master ;)

**Comment by sebastian-nagel** [comment]
+1  (build and tests are ok, no javadoc errors)

**Comment by lewismc** [comment]
+1, @kamaci do you have write permissions yet? If so then please merge into master.

**Comment by chrismattmann** [comment]
thanks @kamaci merged into master in https://github.com/apache/nutch/commit/3e2d3d456489bf52bc586dae0e2e71fb7aad8fe7

**Pull request merged**
