### PR TITLE
Read Paragraph Line Breaks

### PR DESCRIPTION
**Pull request by vipulbehl**
Added condition that will separate paragraph line breaks.

### CODE REVIEW

**Comment by lewismc** [comment]
Any objections to commit to master?

**Comment by lewismc** [comment]
@vipulbehl thank you for the contribution. Was there a JIRA issue filed for this?

**Comment by vipulbehl** [comment]
@lewismc no, there was no JIRA issue filed for this. I was just using this repo and found this issue so I created a pull request. If you want I can create a JIRA issue for the same.

**Comment by lewismc** [comment]
No it's okday now. Thank you for the contribution. If you feel like contributing to Nutch again please open a JIRA issue Thank you very much for the contribution.

**Comment by vipulbehl** [comment]
Ok sure, thank you for the merge.

**Comment by sebastian-nagel** [comment]
(it's late I know)
- this commit makes the nightly tests fail ([#3431](https://builds.apache.org/view/M-R/view/Nutch/job/Nutch-trunk/3431/))
- I would recommend to always open a Jira issue - for release reports and also because build failures are tracked there but not here on github
- please, also run `ant clean runtime test` to test patches/PRs

@vipulbehl: thanks, that's an improvement, having the complete text in a single line. However,
- the solution adds a lot of superfluous line breaks and spaces at the beginning of each line / paragraph (that actually breaks existing tests)
- it's only done in parse-tika, it would be nice to port the solution to parse-html

**Comment by sebastian-nagel** [comment]
To get this sorted out quickly: opened [NUTCH-2397](https://issues.apache.org/jira/browse/NUTCH-2397), fix/PR is ready.

**Pull request merged**
