### PR TITLE
NUTCH-2845 Complete rules of urlfilter-suffix

### PR DESCRIPTION
**Pull request by sebastian-nagel**
add more excluded file suffixes for
- images
- audio and video formats
- software packages and archives
- fonts

### CODE REVIEW

**Comment by sebastian-nagel** [comment]
Below the mapping of file suffixes to file formats or MIME types:
```
.3g2	3GPP2 Multimedia
.3gp	video/3gpp
.afm	application/x-font-adobe-metric
.aif	audio/x-aiff
.aiff	audio/x-aiff
.apk	application/vnd.android.package-archive
.avif	video/quicktime
.bz2	application/x-bzip2
.crx	application/x-chrome-package
.dll	Microsoft dynamic-link library
.dmg	Apple Disk Image
.egg	Egg Python package
.f4v	video/quicktime
.flac	audio/x-flac
.gblorb	audio/x-aiff
.gifv	image/gif
.icns	Apple Icon Image
.ipk	Debian software installation package
.jp2	image/jp2
.jpf	image/jpx
.jpx	image/jpx
.js	application/javascript
.kdc	image/x-raw-kodak
.lzma	application/x-lzma
.m3u8	audio/x-mpegurl
.m4a	video/mp4
.m4r	iPhone Ringtone
.m4v	video/x-m4v
.mar	Mozilla Archive
.mk3d	Matroska 3D Video
.mka	Matroska Audio
.mks	Matroska Elementary Stream
.mkv	video/x-matroska
.movie	video/x-sgi-movie
.mp4	video/mp4
.mp4a	audio/mp4
.mpga	audio/mpeg
.oga	audio/vorbis
.opus	audio/opus
.otf	application/x-font-otf
.pfb	application/x-font-type1
.qt	Apple QuickTime Movie
.rar	application/x-rar-compressed
.svg	image/svg+xml
.svgz	image/svg+xml
.ttf	application/x-font-ttf
.udeb	application/x-debian-package
.webm	video/webm
.webp	image/webp
.whl	Wheel Python package
.woff	application/font-woff
.woff2	application/font-woff2
.xm	audio/xm
.xz	application/x-xz
```

**Comment by lewismc** [comment]
Hi @sebastian-nagel I'm curious. Does Tika not process these files or do we generally just want to avoid them? Thanks

**Comment by lewismc** [comment]
For example, we were planning on starting work on https://issues.apache.org/jira/browse/TIKA-94 which would facilitate extraction of text from more multimedia. Thanks for any insights.

**Comment by sebastian-nagel** [comment]
Hi @lewismc, the template rules of urlfilter-suffix already include suffixes typically indicating image, video, package and binary formats. But the suffix set dates back to 2006 (34067f7), so this PR adds suffixes for recent formats, e.g. if .png and .jpg are excluded excluded, also .webp should.

Whether or not a crawl shall include multimedia content depends on the use case. By default, urlfilter-suffix is not included in plugin.includes. Even if Tika can extract text from many multimedia and package formats - there's a tradeoff between bandwidth and outcome. While HTML pages are usually small (even smaller with compression during HTTP transfer), crawling multimedia files or software packages can consume a substantial part of your network bandwidth.

But again: it's on the users to enable the suffix filter and to modify the rules at their needs.

**Comment by lewismc** [comment]
Thanks @sebastian-nagel +1

**Pull request merged**
