### PR TITLE
NUTCH-3044 Generator: NPE when extracting the host part of a URL fails

### PR DESCRIPTION
**Pull request by sebastian-nagel**

### CODE REVIEW

**Review by lewismc — APPROVED** [review]
+1 LGTM

I was thinking we could provide a `TestGenerator#testNullHostInReducer` test case which would bootstrap the `SelectorReducer.reduce` with some "well formed" and "not well-formed" URLs in order to validate that no NPE is thrown. The test case should fail before your patch is applied and pass afterwards.

**Comment by sebastian-nagel** [comment]
> we could provide a TestGenerator#testNullHostInReducer test case

Good idea! Done, see 4729786.

**Comment by sebastian-nagel** [comment]
... also fixed the Javadoc error.

**Comment by lewismc** [comment]
Excellent @sebastian-nagel +1

**Pull request merged**
