### PR TITLE
NUTCH-1541 Indexer plugin to write CSV

### PR DESCRIPTION
**Pull request by sebastian-nagel**
- adds an indexer plugin which writes a configurable CSV index
- works only in local mode in combination with `-noCommit`
```
CSVIndexWriter - write index as CSV file (comma separated values)
  indexer.csv.fields       : ordered list of fields (columns) in the CSV file
  indexer.csv.separator    : separator between fields (columns), default: , (U+002C, comma)
  indexer.csv.quotechar    : quote character used to quote fields containing separators or quotes, default: " (U+0022, quotation mark)
  indexer.csv.escapechar   : escape character used to escape a quote character, default: " (U+0022, quotation mark)
  indexer.csv.recordsep    : separator between records (rows) resp. documents, default: \r\n (DOS-style line breaks)
  indexer.csv.valuesep     : separator between multiple values of one field, default: | (U+007C)
  indexer.csv.maxfieldvalues : max. number of values of one field, useful for,  e.g., the anchor texts field, default: 12
  indexer.csv.maxfieldlength : max. length of a single field value in characters, default: 4096.
  indexer.csv.charset      : encoding of CSV file, default: UTF-8
  indexer.csv.header       : write CSV column headers, default: true
  indexer.csv.outpath      : output path / directory, default: csvindexwriter. 
    CAVEAT: existing output directories are removed!
```

### CODE REVIEW

**Comment by okedoki** [comment]
Hi @sebastian-nagel ,
I have the following exception, I'm not sure that it is related to the distributed mode

Error: java.lang.StringIndexOutOfBoundsException: String index out of range: -2827 at java.lang.String.substring(String.java:1967) at org.apache.nutch.indexwriter.csv.CSVIndexWriter.writeEscaped(CSVIndexWriter.java:357) at org.apache.nutch.indexwriter.csv.CSVIndexWriter.writeQuoted(CSVIndexWriter.java:320) at org.apache.nutch.indexwriter.csv.CSVIndexWriter.write(CSVIndexWriter.java:248) at org.apache.nutch.indexer.IndexWriters.write(IndexWriters.java:87) at org.apache.nutch.indexer.IndexerOutputFormat$1.write(IndexerOutputFormat.java:50) at org.apache.nutch.indexer.IndexerOutputFormat$1.write(IndexerOutputFormat.java:41) at org.apache.hadoop.mapred.ReduceTask$OldTrackingRecordWriter.write(ReduceTask.java:493) at org.apache.hadoop.mapred.ReduceTask$3.collect(ReduceTask.java:422) at org.apache.nutch.indexer.IndexerMapReduce.reduce(IndexerMapReduce.java:369) at org.apache.nutch.indexer.IndexerMapReduce.reduce(IndexerMapReduce.java:57) at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:444) at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:392) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:170) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:422) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1866) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:164)


It happens when it tries to write escape characters for some string like this
6 GT
Année 2017-2018 Deuxième degré (orientation) :
Quatrième année de l’enseignement
de transition de qualification
général technique technique professionnel
Classe 4 GT 4 GT 4 GT 4 TT 4 TQA 4 TQR 4 PR 4 PV
Option principale
S c ie
n c e s
S c ie
n c e s
é c o
n o
m iq
u e s
S c ie
n c e s
s o
c ia
le s
E d
u c a ti
o n
p
h y s iq
u e
T e c h
n iq

What is kind of strange because in my version of Nutch all punctuation characters should be deleted.
The other lines look like this and parsed correctly:
atletica de sports aerobics club voor jou atletica de sports aerobics club

**Comment by sebastian-nagel** [comment]
Hi @okedoki, something's weird, the line numbers in the stack do not correspond to the source code:
```
org.apache.nutch.indexwriter.csv.CSVIndexWriter.writeEscaped(CSVIndexWriter.java:357) at org.apache.nutch.indexwriter.csv.CSVIndexWriter.writeQuoted(CSVIndexWriter.java:320) at org.apache.nutch.indexwriter.csv.CSVIndexWriter.write(CSVIndexWriter.java:248) at 
```
E.g., writeQuoted() starts in [line 365](https://github.com/sebastian-nagel/nutch/blob/a8e59ec2c6dc4f61acdc33bf42f4a7eb98e98663/src/plugin/indexer-csv/src/java/org/apache/nutch/indexwriter/csv/CSVIndexWriter.java#L365). Are you testing an earlier patch?

**Comment by okedoki** [comment]
Yes, I tested it with patch-2.
Need to rerun it with the new one.

**Comment by r0ann3l** [comment]
Hi @sebastian-nagel, good job!!! After merging the master there are some conflicts associated with changes made by [NUTCH-1480](https://issues.apache.org/jira/browse/NUTCH-1480). I've tried to fix these issues in [here](https://github.com/r0ann3l/nutch/commits/NUTCH-1541). You can to pick them from there.

In addition, the options of this plugin should be migrated from the file nutch-site.xml to index-writers.xml as proposed by [NUTCH-1480](https://issues.apache.org/jira/browse/NUTCH-1480) and perhaps the prefix "indexer.csv." could be removed, because the index-writers.xml file avoids ambiguity across the index writers.

As a recommendation I believe the static attributes you're using should be moved to an interface, how we have been doing in other indexers. I can contribute if you are agree with me.

**Comment by sebastian-nagel** [comment]
Hi @r0ann3l, I'm happy if you could take over and make this plugin work with the new indexer plugin configuration. Feel free to clean-up the code. Thanks! It could be a useful plugin for debugging or if the data is used for data mining. Right now, it will only work in local mode. In distributed mode with big data, you would probably use a more efficient format anyway.

**Comment by sebastian-nagel** [comment]
Thanks, @r0ann3l! I've adapted the unit tests to use the `open(params)` (NUTCH-1480).

**Comment by sebastian-nagel** [comment]
Ok, but looks the plugin needs also to be added to `conf/index-writers.xml.template`. By adding only `indexer-csv` to plugin.includes I get:
```
2018-07-05 16:45:15,215 INFO  indexer.IndexWriters - Index writer org.apache.nutch.indexwriter.csv.CSVIndexWriter identified.
2018-07-05 16:45:15,242 INFO  indexer.IndexingJob - No IndexWriters activated - check your configuration
```

**Comment by r0ann3l** [comment]
Yes, I'm working on that. I will provide new commits soon. Thanks!!!

**Comment by r0ann3l** [comment]
Hi @sebastian-nagel I think the plugin is ready to be used out-of-the-box now. A relevant change I made is: the `recordsep` param is no longer configurable because when `\r\n` (default value) is read from `conf/index-writers.xml` file then we get printed the string `\r\n` (Discussion about this [here](https://stackoverflow.com/questions/19188662/n-not-working-when-reading-from-file-to-list-and-then-to-output-java))

**Comment by r0ann3l** [comment]
I think the method `describe()` must be changed to support [NUTCH-2602](https://issues.apache.org/jira/browse/NUTCH-2602).

**Comment by sebastian-nagel** [comment]
Hi @r0ann3l, the unit tests fail to compile. Could you fix and run them? The easiest way is `ant test-plugin -Dplugin=indexer-csv`.
Yes, of course, it's ok to change the describe method (for this PR or in NUTCH-2602/#356).

**Comment by r0ann3l** [comment]
Hi @sebastian-nagel, I think is better in NUTCH-2602 but we have to merge this PR first, right?

**Comment by sebastian-nagel** [comment]
+1 Please go ahead and merge. Thanks, @r0ann3l!
- unit tests pass
- successfully indexed into CSV using default configuration:
```
% bin/nutch index -Dplugin.includes='indexer-csv|index-(basic|anchor|more)' \
     crawl/crawldb/ -dir crawl/segments/ -noCommit -deleteGone
Indexer: number of documents indexed, deleted, or skipped:
Indexer:      4  deleted (gone)
Indexer:     35  indexed (add/update)

% head -2 csvindexwriter/nutch.csv 
id,title,content
http://nutch.apache.org/,Apache Nutch™ -,"Apache Nutch™ -
```
- I had to remove or change exchange.xml to avoid that the Exchange component still tries to route documents to indexer_solr_1, see NUTCH-2617

**Comment by grege117** [comment]
Sorry to chime in a few years late, but I'm not sure this plugin is configured correctly.

If I modify my conf/index-writers.xml and remove everything except for "<writer id="indexer_csv_1">, you will get the message:

IndexerOutputFormat [pool-5-thread-1] No IndexWriters activated - check your configuration

The only way I could write to CSV was to execute what @sebastian-nagel  wrote above:
bin/nutch index -Dplugin.includes='indexer-csv' crawl/crawldb/ -linkdb crawl/linkdb/ crawl/segments/20231222132024/ -filter -normalize -deleteGone


However, if I add back in the index-writer for SOLR, that just works (no -Dplugin.includes is required).  

So I think there's a bug here in the OOTB configuration that prevents indexer-csv working without specifying it on the CLI.

**Comment by lewismc** [comment]
Hi @grege117 I’ll try to have a crack at this _soon_. Thanks for the heads up. If you feel like forking the branch and having a go at the fix, then please do. I will try to shepherd in your contribution if you can make one!

**Comment by sebastian-nagel** [comment]
Hi @grege117, sorry for the late response. The indexer-csv is not among the plugins activated by default. Only indexer-solr is active by default, see [plugin.includes in nutch-default.xml](https://nutch.apache.org/documentation/javadoc/api/resources/nutch-default.xml#plugin.includes). That explains why you need to override the property `plugin.includes` if you want to use indexer-csv. You can do this in the command-line (`-D...`) or in your nutch-site.xml, see https://cwiki.apache.org/confluence/display/NUTCH/NutchTutorial#NutchTutorial-Customizeyourcrawlproperties

**Pull request merged**
