### PR TITLE
NUTCH-2449: Replace Tika LanguageIdentifier in language-identifier

### PR DESCRIPTION
**Pull request by YossiTamari**
Replaced with Optimaize LanguageDetector, which Tika has moved to as the default LanguageDetector.

### CODE REVIEW

**Comment by YossiTamari** [comment]
If this pull request is accepted, the tests for the language-identifier plugin should be rewritten.

**Comment by lewismc** [comment]
Hi @YossiTamari I think that this feature would be better proposed as a brand new plugin... the existing language-identifier plugin is stable and there is no real reason to get entirely rid of it. There is however always purpose in adding a new plugin... folks can then choose as they wish.
Can you repurpose this pull request to add a new plugin?

**Comment by pipldev** [comment]
Sebastian made the same suggestion, but I really don't like it personally for two reasons:
1. 90% of the code of the plugin would be copied, and somebody would have to manage applying every fix to both plugins.
2. I think it would be really confusing to users to find two plugins that do exactly the same thing, with the only difference being an implementation detail.
Keep in mind that while the the existing plugin is stable, it relies on deprecated code, and presumably would break eventually when Tika decides to remove the deprecated implementation.

**Comment by lewismc** [comment]
@pipldev thanks

> 90% of the code of the plugin would be copied, and somebody would have to manage applying every fix to both plugins.

I agree. There have been VERY few changes to this plugin in almost a decade. I don't anticipate that there will be too many changes moving forward.

> I think it would be really confusing to users to find two plugins that do exactly the same thing, with the only difference being an implementation detail.

Not if it is documented in a README.md contained within the plugin directory. Usually people interested in Linguistics are also very interested in the application or techniques used in tasks such as language identification, statistical machine translations, etc. i think any confusion could be easily avoided if we provide a simple README.

> Keep in mind that while the the existing plugin is stable, it relies on deprecated code, and presumably would break eventually when Tika decides to remove the deprecated implementation.

I agree, but as I said it is stable. We have tight integration between Nutch and Tika dev community. Once the code is removed over in Tika, it is trivial to remove the code over here.

At the end of the day it is down to the contributor if this code is to be updated or not, I just think preservation is an important part of what we do here. Retaining the legacy plugin is doing no harm whatsoever.
Thanks

**Comment by YossiTamari** [comment]
Sorry for the mix-up, pipldev is my alternate account...

Speaking as a relatively new user of Nutch, I have never looked for a readme file in a plugin directory. It's a good thing, since I just sampled a few, and none had a readme file.

In my experience, getting into Nutch is a challenging task, and often requires looking into the code (and often debugging) to understand how things are supposed to work.
I do not think adding one more way to confuse users is a good idea. Just as an example for why it would be so confusing, the plugin has a number of configuration settings. Do we use the same properties to configure both plugins? Do we duplicate all of them in nutch-default.xml and try to explain in the comments there why there are two sets with the exact same functionalities?

**Comment by sebastian-nagel** [comment]
Hi @YossiTamari, finally I've found the time to test the PR. Fetching your branch failed, to resolve conflicts I've created a [new branch](https://github.com/sebastian-nagel/nutch/tree/YossiTamari-NUTCH-2449) and applied your patch. One trivial fix: still need to copy `langmapping.properties` (used to parse HTML lang attribute) to runtime. Everything works fine! If there are no objection I'll merge soon. Thanks!

**Comment by YossiTamari** [comment]
Thanks @sebastian-nagel, note that the tests still use org.apache.tika.language.LanguageIdentifier directly.

**Comment by sebastian-nagel** [comment]
Ok, better to update the tests. Thanks for the hint, @YossiTamari!

**Comment by lewismc** [comment]
@YossiTamari @sebastian-nagel this has been sitting for way too long. By the looks of the above correspondence the decision was made to overwrite the logic in language-identifier with the Optimaize logic.
[Tika LanguageDetector](https://tika.apache.org/2.1.0/api/index.html?org/apache/tika/language/detect/LanguageDetector.html) now offers several implementations which I think we could easily drive through configuration in nutch-default.xml.
Where do we want to go with this one? I can help with the effort.

**Comment by sebastian-nagel** [comment]
Hi @lewismc, via NUTCH-2891/ b0cbea5 we already switched to the Optimaize language detector wrapped by Tika. I have it on my list to verify that this PR (and NUTCH-1397) is resolved en passant but hadn't the time to look over it. If you want, feel free to take over. Thanks!

**Comment by lewismc** [comment]
OK @sebastian-nagel I will take it on yes. I'm nearly finished with my metrics documentation then I'll come back to this one.

**Comment by lewismc** [comment]
Closing this PR off now in place of https://github.com/apache/nutch/pull/716

**Pull request closed without merging**
