### PR TITLE
fix for NUTCH-2015 contributed by Sujen Shah

### PR DESCRIPTION
**Pull request by sujen1412**

### CODE REVIEW

**Comment by chrismattmann** [comment]
@sebastian-nagel FYI, thoughts on this?

**Comment by chrismattmann** [comment]
@sujen1412 where are we at cc @lewismc

**Comment by chrismattmann** [comment]
ping @sujen1412 Asitang @lewismc any progress here?

**Comment by sujen1412** [comment]
Updated PR, please have a look.

**Comment by chrismattmann** [comment]
this LGTM, @sujen1412 - @sebastian-nagel can you take a look?

**Pull request closed without merging**
