### PR TITLE
Fix for Nutch-2246: Refactor /seed end point

### PR DESCRIPTION
**Pull request by sujen1412**

### CODE REVIEW

**Comment by chrismattmann** [comment]
LGTM is this compatible with the Nutch Python interface, Sujen? Can we have an associated PR there. Also we should make some Nutch-Python tests and integrate with Travis-CI like we did Tika Python.

**Comment by sujen1412** [comment]
@chrismattmann, I ran tests with Nutch-Python and both the seed and inject job tests pass with this PR. 
Thanks!

**Comment by chrismattmann** [comment]
👍 from me please commit!

**Comment by chrismattmann** [comment]
@sujen1412 ping

**Comment by sujen1412** [comment]
Committing now @chrismattmann

**Pull request closed without merging**
