### PR TITLE
NUTCH-2731 Fix to ensure that credentials are set on delete operations.

### PR DESCRIPTION
**Pull request by deanpearce**
Thanks for your attention - I have submitted the fix and created the relevant ticket in JIRA. The fix is fairly straightforward, following the same pattern used for commits and writes.

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @deanpearce thanks for the patch. +1

**Comment by mport** [comment]
Awesome! Would really appreciate if this could be merged it into the snapshot soon!

**Comment by sebastian-nagel** [comment]
+1 Lgtm. All tests pass.

**Comment by sebastian-nagel** [comment]
Hi @mport, because the [release procedure](https://cwiki.apache.org/confluence/display/NUTCH/Release_HOWTO) is complex, we used to release patch versions only if a release is essentially non-functional. But the release of 1.16 should land soon. I've just started a thread about it on the [Nutch @dev mailing list](http://www.mail-archive.com/dev%40nutch.apache.org/).

**Pull request merged**
