### PR TITLE
Nutch 2052 - Enhancement to index-static to allow user-defined delimiters for fields

### PR DESCRIPTION
**Pull request by PeterCiuffetti**

### CODE REVIEW

**Comment by chrismattmann** [comment]
I see the following failures with this PR:

```
[mattmann-0420740:~/tmp/nutch-trunk] mattmann% more build/index-static/test/TEST-org.apache.nutch.indexer.staticfield.TestStaticFieldIndexerTest.txt 
Testsuite: org.apache.nutch.indexer.staticfield.TestStaticFieldIndexerTest
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.085 sec

Testcase: testNormalScenario took 0.444 sec
Testcase: testCustomDelimiters took 0.364 sec
        FAILED
test if doc has field1
junit.framework.AssertionFailedError: test if doc has field1
        at org.apache.nutch.indexer.staticfield.TestStaticFieldIndexerTest.testCustomDelimiters(TestStaticFieldIndexerTest.java:149)

Testcase: testEmptyIndexStatic took 0.126 sec
[mattmann-0420740:~/tmp/nutch-trunk] mattmann% 
```

Also to apply it I had to do the following (due to extraneous commits included from lewismc) - please git reset --hard HEAD before updating and pushing your PR.

```
git apply --exclude="*CHANGES.txt" --exclude="*NOTICE.txt" --exclude="*nutch-default.xml" --exclude="*default.properties" < 43.patch
```

**Comment by chrismattmann** [comment]
FYI @PeterCiuffetti

**Comment by PeterCiuffetti** [comment]
Hello Chris...

Thanks for looking at my PR.  Sorry about the unit test failure.  Ive addressed this and added another test case to cover checking delimiters that need regex escaping.

To make applying the patch simple, can you clarify what needs to be done here?   Are you suggesting I remove this PR, apply my changes on a fresh clone of the trunk and do a new pull request on that?   Or is there a set of steps I can do to resolve it in this PR?

Here are the current plugin test results...
```
$ ant test-plugins....

test:
     [echo] Testing plugin: creativecommons
    [junit] Running org.apache.nutch.indexer.basic.TestBasicIndexingFilter
    [junit] Running org.creativecommons.nutch.TestCCParseFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.524 sec

test:
     [echo] Testing plugin: index-anchor
    [junit] Running org.apache.nutch.indexer.anchor.TestAnchorIndexingFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.351 sec

test:
     [echo] Testing plugin: index-more
    [junit] Running org.apache.nutch.indexer.more.TestMoreIndexingFilter
    [junit] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.868 sec

test:
     [echo] Testing plugin: index-static
    [junit] Running org.apache.nutch.indexer.staticfield.TestStaticFieldIndexerTest
    [junit] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.415 sec

test:
     [echo] Testing plugin: language-identifier
    [junit] Running org.apache.nutch.analysis.lang.TestHTMLLanguageParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.741 sec

test:
     [echo] Testing plugin: lib-http
    [junit] Running org.apache.nutch.protocol.http.api.TestRobotRulesParser
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.113 sec

test:
     [echo] Testing plugin: protocol-file
    [junit] Running org.apache.nutch.protocol.file.TestProtocolFile
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.857 sec

test:
     [echo] Testing plugin: protocol-http
    [junit] Running org.apache.nutch.protocol.http.TestProtocolHttp
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.921 sec

test:
     [echo] Testing plugin: protocol-httpclient
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.299 sec

test:
     [echo] Testing plugin: feed
    [junit] Running org.apache.nutch.parse.feed.TestFeedParser
    [junit] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.721 sec

test:
     [echo] Testing plugin: parse-html
    [junit] Running org.apache.nutch.parse.html.TestDOMContentUtils
    [junit] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.726 sec
    [junit] Running org.apache.nutch.parse.html.TestHtmlParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.273 sec

test:
     [echo] Testing plugin: parse-metatags
    [junit] Running org.apache.nutch.parse.metatags.TestMetatagParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.369 sec
    [junit] Running org.apache.nutch.parse.html.TestRobotsMetaProcessor
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.498 sec

test:
     [echo] Testing plugin: parse-swf
    [junit] Running org.apache.nutch.parse.swf.TestSWFParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.034 sec

test:
     [echo] Testing plugin: parse-tika
    [junit] Running org.apache.nutch.tika.TestDOMContentUtils
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.94 sec

test:
     [echo] Testing plugin: parse-zip
    [junit] Running org.apache.nutch.parse.zip.TestZipParser
    [junit] Running org.apache.nutch.tika.TestFeedParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.548 sec
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.901 sec

test:
     [echo] Testing plugin: subcollection
    [junit] Running org.apache.nutch.tika.TestImageMetadata
    [junit] Running org.apache.nutch.collection.TestSubcollection
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.445 sec

test:
     [echo] Testing plugin: urlfilter-automaton
    [junit] Running org.apache.nutch.urlfilter.automaton.TestAutomatonURLFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.691 sec
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.104 sec

test:
     [echo] Testing plugin: urlfilter-domain
    [junit] Running org.apache.nutch.tika.TestMSWordParser
    [junit] Running org.apache.nutch.urlfilter.domain.TestDomainURLFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.737 sec

test:
     [echo] Testing plugin: urlfilter-domainblacklist
    [junit] Running org.apache.nutch.urlfilter.domainblacklist.TestDomainBlacklistURLFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.72 sec

test:
     [echo] Testing plugin: urlfilter-prefix
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.872 sec
    [junit] Running org.apache.nutch.urlfilter.prefix.TestPrefixURLFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.115 sec

test:
     [echo] Testing plugin: urlfilter-regex
    [junit] Running org.apache.nutch.tika.TestOOParser
    [junit] Running org.apache.nutch.urlfilter.regex.TestRegexURLFilter
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.52 sec
    [junit] Running org.apache.nutch.tika.TestPdfParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.751 sec

test:
     [echo] Testing plugin: urlfilter-suffix
    [junit] Running org.apache.nutch.urlfilter.suffix.TestSuffixURLFilter
    [junit] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 sec

test:
     [echo] Testing plugin: urlfilter-validator
    [junit] 2015-07-02 15:18:20.764 java[29349:1903] Unable to load realm info from SCDynamicStore
    [junit] Running org.apache.nutch.urlfilter.validator.TestUrlValidator
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.033 sec

test:
     [echo] Testing plugin: urlnormalizer-ajax
    [junit] Running org.apache.nutch.net.urlnormalizer.ajax.TestAjaxURLNormalizer
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.011 sec

test:
     [echo] Testing plugin: urlnormalizer-basic
    [junit] Running org.apache.nutch.net.urlnormalizer.basic.TestBasicURLNormalizer
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.25 sec

test:
     [echo] Testing plugin: urlnormalizer-host
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.98 sec
    [junit] Running org.apache.nutch.net.urlnormalizer.host.TestHostURLNormalizer
    [junit] Running org.apache.nutch.tika.TestRTFParser
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.025 sec
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.498 sec

test:
     [echo] Testing plugin: urlnormalizer-pass
    [junit] Running org.apache.nutch.tika.TestRobotsMetaProcessor
    [junit] Running org.apache.nutch.net.urlnormalizer.pass.TestPassURLNormalizer
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.226 sec

test:
     [echo] Testing plugin: urlnormalizer-regex
    [junit] Running org.apache.nutch.net.urlnormalizer.querystring.TestQuerystringURLNormalizer
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.224 sec

test:
     [echo] Testing plugin: urlnormalizer-slash
    [junit] Running org.apache.nutch.net.urlnormalizer.regex.TestRegexURLNormalizer
    [junit] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.361 sec
    [junit] Running org.apache.nutch.net.urlnormalizer.slash.TestSlashURLNormalizer
    [junit] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.408 sec

BUILD SUCCESSFUL
Total time: 1 minute 15 seconds
```

**Comment by chrismattmann** [comment]
Yep just submitting an updated branch to this pr would be great thanks

**Comment by PeterCiuffetti** [comment]
Ok, heres the steps I did... does this cover it?

```
git checkout NUTCH-2052
git pull origin trunk
git reset --hard HEAD
[fixed the unit test failures]
git commit -a -m"Escapng regexp chars when used as delimiters"
[fixed a code formatting issue]
git commit -a -m"Formatting change"
git push -u git@github.com:PeterCiuffetti/nutch.git NUTCH-2052
```

**Comment by chrismattmann** [comment]
Yep! Will commit shortly

**Comment by chrismattmann** [comment]
Hey @PeterCiuffetti there is a randomly occurring test error here:

```
    [junit] Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 64.156 sec
    [junit] Test org.apache.nutch.protocol.httpclient.TestProtocolHttpClient FAILED
```

Thoughts?

**Comment by PeterCiuffetti** [comment]
I'd be happy to investigate..  Im not able to repeat it though.  Is this happening on Jenkins? on the trunk?  Can you paste the TEST-org.apache.nutch.protocol.httpclient.TestProtocolHttpClient.txt with the error?

While the test passes for me, I am noticing that it logs several copies of this exception:
```
java.lang.IllegalStateException: STREAM
        at org.mortbay.jetty.Response.getWriter(Response.java:616)
```
Which suggest something not right in the jsp's being used.

**Comment by chrismattmann** [comment]
yeah i'm getting that same error. The first time it failed for me, then it passed. I can't see the builds.apache.org jenkins output, but I can try testing again. Let me try that. @PeterCiuffetti

**Comment by PeterCiuffetti** [comment]
I can make the exceptions go away if I adjust the JSPs.  This is an artifact of white space outside the code blocks.  Eg.

```
--%>
<%--
```
...which you will find in scattered places in the JSP like here: https://github.com/apache/nutch/blob/trunk/src/plugin/protocol-httpclient/jsp/basic.jsp#L15, needs to become...
```
--%><%--
```
This prevents the response writer from being unnecessarily invoked on a page that may decide (later) to do a redirect (https://github.com/apache/nutch/blob/trunk/src/plugin/protocol-httpclient/jsp/basic.jsp#L65).  What jetty is complaining about is that the response is already in flight at the point where the page decides to send some headers.

So while this is easy to fix (remove all unnecessary white space outside code blocks) Im not sure if this is the smoking gun.

I see its failing on jenkins here:
https://builds.apache.org/view/All/job/Nutch-trunk/3190/consoleFull
```
test:
     [echo] Testing plugin: protocol-httpclient
    [junit] Running org.apache.nutch.protocol.http.TestProtocolHttp
    [junit] WARNING: multiple versions of ant detected in path for junit 
    [junit]          jar:file:/home/jenkins/tools/ant/latest/lib/ant.jar!/org/apache/tools/ant/Project.class
    [junit]      and jar:file:/home/jenkins/jenkins-slave/workspace/Nutch-trunk/trunk/build/test/lib/ant-1.6.5.jar!/org/apache/tools/ant/Project.class
    [junit] Running org.apache.nutch.protocol.httpclient.TestProtocolHttpClient
    [junit] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.377 sec
    [junit] Test org.apache.nutch.protocol.http.TestProtocolHttp FAILED
```
...but but it would be nice to see what the error was.

I can submit a patch to the JSPs.  Is there already a JIRA ticket for this?

**Comment by PeterCiuffetti** [comment]
I've created https://issues.apache.org/jira/browse/NUTCH-2059

I notice in the Jenkins log that the failure may be either for protocol-httpclient (see console output for job 3190 this afternoon) or protocol-http (see console output for job 3189 this morning)

Given that the unit tests are multi-threaded, I wonder if its related to https://issues.apache.org/jira/browse/NUTCH-1836

**Comment by PeterCiuffetti** [comment]
Iv pushed a fix for the illegal state exception to a branch on my github account
https://github.com/PeterCiuffetti/nutch/commit/2ac9a4bf251d0b7b5b9d14bb7596b790d67bd785

...Ill wait to do a PR until I explore NUTCH-1836 a bit

**Comment by chrismattmann** [comment]
thanks for the patch, @PeterCiuffetti . I applied it. Looks like it worked once, then failed on the next build. Not sure it seems like it's sporadic.

**Pull request closed without merging**
