### PR TITLE
NUTCH-2980: Upgraded Selenium to 4.7.2 + HTMLUnit

### PR DESCRIPTION
**Pull request by KamilMroczek**
- Disabled phantomJS driver as it was causing problems casting TakeScreenshot to HtmlUnitWebDriver and the project has been archived since 2018
- Improved README setup instructions for IntelliJ

The following libraries were added as part of the selenium-java and htmlunit upgrades. They are all Apache 2.0, MIT or EDL.

async-http-client
async-http-client-netty-utils
auto-common
auto-service
auto-service-annotations
checker-qual
dec
failsafe
failureaccess
htmlunit-xpath
jakarta.activation
jcommander
jtoml
listenablefuture
netty-buffer
netty-codec
netty-codec-http
netty-codec-socks
netty-common
netty-handler
netty-handler-proxy
netty-reactive-streams
netty-resolver
netty-transport
netty-transport-classes-epoll
netty-transport-classes-kqueue
netty-transport-native-epoll
netty-transport-native-kqueue
netty-transport-native-unix-common
opentelemetry-api
opentelemetry-api-logs
opentelemetry-context
opentelemetry-exporter-common
opentelemetry-exporter-logging
opentelemetry-sdk
opentelemetry-sdk-common
opentelemetry-sdk-extension-autoconfigure
opentelemetry-sdk-extension-autoconfigure-spi
opentelemetry-sdk-logs
opentelemetry-sdk-metrics
opentelemetry-sdk-trace
opentelemetry-semconv
reactive-streams
salvation2
selenium-chromium-driver
selenium-devtools-v106
selenium-devtools-v107
selenium-devtools-v108
selenium-devtools-v85
selenium-http
selenium-json
selenium-manager

### CODE REVIEW

**Review by sebastian-nagel — APPROVED** [review]
Hi, @KamilMroczek! Looks good. I'll give it a trial later today. Esp. thanks for updating the README and verifying whether software licenses are compatible!

**Comment by sebastian-nagel** [comment]
Hi @KamilMroczek, indeed - keeping the licenses up-to-date is a difficult task. See also NUTCH-2290 and NUTCH-2981. 

Unfortunately, so far I wasn't able to successfully test protocol-selenium and this PR. But this is on my side. Both Chrome and Firefox (recent browser and driver versions) show up (in headful mode) but for some reason the driver than times out with obscure error messages. It's reproducible from Python, so it's something with my system (maybe because I recently switched to use Wayland instead of X11). Will try it on a different system...

**Comment by KamilMroczek** [comment]
Ok. I was able to run in local mode on mac with firefox & chrome. And also on AWS Linux with Chrome.

**Comment by sebastian-nagel** [comment]
Finally, I was able to successfully test it - the reason was that on recent Ubuntu systems Firefox and Chromium are installed as snap packages. This adds extra sandboxing and requires that `TMPDIR` points to a folder the snap packages are allowed to write to (they cannot write to the default `/tmp/`).

Thanks, @KamilMroczek !

**Pull request merged**
