### PR TITLE
fix for NUTCH-2911 contributed by prakharchaube

### PR DESCRIPTION
**Pull request by prakharchaube**
Fix for [NUTCH-2911](https://issues.apache.org/jira/browse/NUTCH-2911)

Changes made : Added a wrapper try-finally block for FetcherRun.run() and called cleanup()

### CODE REVIEW

**Comment by sebastian-nagel** [comment]
Thanks @prakharchaube, good catch. The compilation fails with `Fetcher.java:440: error: unreported exception InterruptedException; must be caught or declared to be thrown` - could you update the PR to catch the exception thrown by the [cleanup](https://hadoop.apache.org/docs/r3.3.1/api/org/apache/hadoop/mapreduce/Mapper.html#cleanup-org.apache.hadoop.mapreduce.Mapper.Context-) method. Thanks!

**Comment by prakharchaube** [comment]
@sebastian-nagel I have added a catch for InterruptedException, sorry for missing it. I know ideally, we should not catch InterruptedException and simply log it, but the cleanup() call will never throw it in the first place.
Let me know if there are any concerns around this. Thanks.

**Comment by sebastian-nagel** [comment]
Hi @prakharchaube, after a second look (sorry about it), you're right.

> ideally, we should not catch InterruptedException

Definitely. The overridden [Mapper run](https://hadoop.apache.org/docs/r3.3.1/api/org/apache/hadoop/mapreduce/Mapper.html#run-org.apache.hadoop.mapreduce.Mapper.Context-) method declares the InterruptedException to be thrown, so the overriding method should just throw it as well. What do you think?

**Comment by prakharchaube** [comment]
Yes @sebastian-nagel I do feel that would be the best way to handle it, I noticed even job.waitForCompletion() throws InterruptedException so propagation is intentional, I will make the change and update, thanks.

**Comment by prakharchaube** [comment]
Done @sebastian-nagel, please review. Thanks!

**Review by sebastian-nagel — APPROVED** [review]
Thanks, @prakharchaube! Looks good. Waiting for the CI build and eventual further comments. If there are no objections, will commit soon.

**Pull request merged**
