### PR TITLE
NUTCH-2919 Upgrade to Tika 2.2.1 and Any23 2.6

### PR DESCRIPTION
**Pull request by lewismc**
This PR addresses [NUTCH-2919](https://issues.apache.org/jira/browse/NUTCH-2919)
I'm performing some tests.

### CODE REVIEW

**Comment by lewismc** [comment]
I was getting a local failure on [parse-tika's TestRTFParser](https://github.com/apache/nutch/blob/master/src/plugin/parse-tika/src/test/org/apache/nutch/parse/tika/TestRTFParser.java#L63) where it was attempting to use the deprecated [org.apache.tika.metadata.OfficeOpenXMLCore#SUBJECT](https://github.com/apache/tika/blob/main/tika-core/src/main/java/org/apache/tika/metadata/OfficeOpenXMLCore.java#L71-L77). This has been replaced by [DublinCore#SUBJECT](https://github.com/apache/tika/blob/main/tika-core/src/main/java/org/apache/tika/metadata/DublinCore.java#L162-L170)

Tests passed locally. Let's see how CI does.

Additionally, when inspecting the extracted metadata from the sample `.rtf` file, I see the following... should we augment the unit test to assert the results?
```
Content-Length: 2235
Content-Type: application/rtf
X-TIKA:Parsed-By: org.apache.tika.parser.DefaultParser
X-TIKA:Parsed-By: org.apache.tika.parser.microsoft.rtf.RTFParser
X-TIKA:digest:MD5: 61d9f6cd7ebacf61737936f9341c2289
X-TIKA:digest:SHA256: 1aae10f9ae8fdfdfddae338dec7f4a40cf9fc7d0c254af32e742dbd227f9399b
dc:subject: tests
dc:title: test rft document
dcterms:created: 2004-09-21T02:36:00Z
resourceName: test.rtf
w:Comments: StarWriter
```

**Comment by lewismc** [comment]
CI was failing with the tests to the `any23` plugin. This makes some kind of sense as the Tika version included in Any23 may be in conflict with Tika 2.2.0.
I've temporarily disabled the `any23` plugin in this PR to see the results. 
Over in Any23 we already use Tika 2.2.0 and each and every dependency is kept up-to-date with Dependabot. We just need to release Any23 2.6.0 but we don't have enough votes quite yet.

**Comment by lewismc** [comment]
To achieve a successful CI build I also had to disable the `ant javadoc` target. The problem here is definitely Any23.
This can be fixed in the next Any23 release by setting the Tika depdency scopes to **provided**, meaning that the expectation is that they will be provided at runtime... which will be true if we upgrade to Tika 2.2.0.
I'll get to work on another release candidate for Any23...

**Comment by lewismc** [comment]
I just created a [2nd release candidate for Any23 2.6](https://lists.apache.org/thread/0x6jfkd9vkdkwq63chd7jl8j09lgkjtf) which ships with Tika 2.2.1.
I will augment this pull request in due course... hopefully once Any23 2.6 has been released.

**Comment by kennethmcfarland** [comment]
Hi Lewis, this is off topic but thanks for being such a great inspiration
when I needed it a few years ago. Sorry I didnt get to do GSOC with you, Im
36 now and have no interest in school, I dont want recognition or pay. Just
wanted to let you know you really changed my life by being so
compassionate. This world needs more like you man. Should I spring for one
of those Lord / Lady (if married) packs so you can go by Lord Lewis John
McGibbney? LOL. TTYL gotta focus on repairing the trauma I'm working thru.
<3 -Kenny

**Comment by lewismc** [comment]
May the force be with you @kennethmcfarland . Take care my friend.

**Comment by lewismc** [comment]
I just released Any23 2.6. I will update this PR once the release has hit the CDN.

**Comment by lewismc** [comment]
This PR also upgrades to Any23 2.6 to resolve potential classpath issues.

**Comment by lewismc** [comment]
Anyone able to try this patch out?

**Review by sebastian-nagel — APPROVED** [review]
Hi @lewismc, looks good!
- tested in local mode: everything looks fine for both parse-tika and any23
- tried on a Hadoop cluster: here I've found a dependency issue with commons-io: Tika uses 2.11.0 but the used Hadoop (Bigtop 3.0.0) ships with 2.5 - I'll try whether not excluding commons-io from the parse-tika dependencies fixes the problem. If yes, it'd be worth to keep the duplicated dependency. But I'll open a separate issue - the rule to exclude commons-io was already there.

**Comment by sebastian-nagel** [comment]
Ok, the dependency conflict with commons-io is tracked in NUTCH-2937.

**Comment by lewismc** [comment]
Thanks @sebastian-nagel

**Pull request merged**
