### PR TITLE
NUTCH-2502: Add Content-Type filter option to Any23 plugin

### PR DESCRIPTION
**Pull request by mfeltscher**

### CODE REVIEW

**Comment by nmaro** [comment]
LGTM

**Comment by lewismc** [comment]
@mfeltscher no it is not intended, I will investigate

**Comment by lewismc** [comment]
I think it was just that the issue title was not the same

**Comment by mfeltscher** [comment]
@lewismc AFAIK this used to work just fine before, take #278 for instance where the title matches the JIRA issue number exactly.

**Comment by lewismc** [comment]
@mfeltscher ack, I will scope it out with INFRA

**Comment by mfeltscher** [comment]
@lewismc Thanks!

**Pull request merged**
