### PR TITLE
NUTCH-2281 Support non-default FileSystem

### PR DESCRIPTION
**Pull request by sebastian-nagel**
Instead of
  FileSystem fs = FileSystem.get(getConf());
use
  FileSystem fs = path.getFileSystem(getConf());
to make sure that FileSystem and Path match.

### CODE REVIEW

**Comment by lewismc** [comment]
Pull patch, ran tests and demo crawl all good. Readsegs, read db, dump and
index to Solr all good.

+1

On Friday, June 17, 2016, Sebastian Nagel <notifications@github.com> wrote:

> Instead of
> FileSystem fs = FileSystem.get(getConf());
> use
> FileSystem fs = path.getFileSystem(getConf());
> to avoid that FileSystem and Path match.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apache/nutch/pull/119
> Commit Summary
>
>    - NUTCH-2281 Support non-default FileSystem
>
> File Changes
>
>    - *M* src/java/org/apache/nutch/crawl/CrawlDb.java
>    <https://github.com/apache/nutch/pull/119/files#diff-0> (18)
>    - *M* src/java/org/apache/nutch/crawl/CrawlDbMerger.java
>    <https://github.com/apache/nutch/pull/119/files#diff-1> (4)
>    - *M* src/java/org/apache/nutch/crawl/CrawlDbReader.java
>    <https://github.com/apache/nutch/pull/119/files#diff-2> (10)
>    - *M* src/java/org/apache/nutch/crawl/DeduplicationJob.java
>    <https://github.com/apache/nutch/pull/119/files#diff-3> (2)
>    - *M* src/java/org/apache/nutch/crawl/Generator.java
>    <https://github.com/apache/nutch/pull/119/files#diff-4> (18)
>    - *M* src/java/org/apache/nutch/crawl/Injector.java
>    <https://github.com/apache/nutch/pull/119/files#diff-5> (2)
>    - *M* src/java/org/apache/nutch/crawl/LinkDb.java
>    <https://github.com/apache/nutch/pull/119/files#diff-6> (15)
>    - *M* src/java/org/apache/nutch/crawl/LinkDbMerger.java
>    <https://github.com/apache/nutch/pull/119/files#diff-7> (2)
>    - *M* src/java/org/apache/nutch/crawl/LinkDbReader.java
>    <https://github.com/apache/nutch/pull/119/files#diff-8> (2)
>    - *M* src/java/org/apache/nutch/hostdb/UpdateHostDb.java
>    <https://github.com/apache/nutch/pull/119/files#diff-9> (2)
>    - *M* src/java/org/apache/nutch/indexer/IndexerMapReduce.java
>    <https://github.com/apache/nutch/pull/119/files#diff-10> (2)
>    - *M* src/java/org/apache/nutch/indexer/IndexingJob.java
>    <https://github.com/apache/nutch/pull/119/files#diff-11> (2)
>    - *M* src/java/org/apache/nutch/parse/ParseSegment.java
>    <https://github.com/apache/nutch/pull/119/files#diff-12> (10)
>    - *M* src/java/org/apache/nutch/scoring/webgraph/LinkDumper.java
>    <https://github.com/apache/nutch/pull/119/files#diff-13> (4)
>    - *M* src/java/org/apache/nutch/scoring/webgraph/LinkRank.java
>    <https://github.com/apache/nutch/pull/119/files#diff-14> (2)
>    - *M* src/java/org/apache/nutch/scoring/webgraph/NodeReader.java
>    <https://github.com/apache/nutch/pull/119/files#diff-15> (3)
>    - *M* src/java/org/apache/nutch/scoring/webgraph/ScoreUpdater.java
>    <https://github.com/apache/nutch/pull/119/files#diff-16> (2)
>    - *M* src/java/org/apache/nutch/scoring/webgraph/WebGraph.java
>    <https://github.com/apache/nutch/pull/119/files#diff-17> (7)
>    - *M* src/java/org/apache/nutch/segment/SegmentMerger.java
>    <https://github.com/apache/nutch/pull/119/files#diff-18> (7)
>    - *M* src/java/org/apache/nutch/segment/SegmentReader.java
>    <https://github.com/apache/nutch/pull/119/files#diff-19> (23)
>    - *M* src/java/org/apache/nutch/tools/CommonCrawlDataDumper.java
>    <https://github.com/apache/nutch/pull/119/files#diff-20> (4)
>    - *M* src/java/org/apache/nutch/tools/FileDumper.java
>    <https://github.com/apache/nutch/pull/119/files#diff-21> (4)
>    - *M* src/java/org/apache/nutch/util/LockUtil.java
>    <https://github.com/apache/nutch/pull/119/files#diff-22> (43)
>
> Patch Links:
>
>    - https://github.com/apache/nutch/pull/119.patch
>    - https://github.com/apache/nutch/pull/119.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apache/nutch/pull/119>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABHJl_wx7qq1X1C8Hp7YuWvkcUcla64Eks5qMqMggaJpZM4I4XXK>
> .
>


-- 
*Lewis*

**Comment by sebastian-nagel** [comment]
Thanks, I'll continue "real-world testing" by reading/writing from/to AWS S3 and will commit in a couple of days if everything is fine.

**Comment by sebastian-nagel** [comment]
Real-world testing continued over two [Common Crawl](http://commoncrawl.org/) monthly crawls.
There is still one problem: if data is moved from one file system to another this fails with the current patch. E.g., CrawlDbMerger creates a temporary output `crawldb-merge-xxxx` on the default file system (HDFS). Calling `fs.rename(...)` (`fs` being the output file system, here s3a) then fails:
```
16/07/22 18:13:42 ERROR s3a.S3AFileSystem: rename: src not found hdfs://ip-10-185-27-174.ec2.internal/user/ubuntu/crawldb-merge-2766889
```
Not sure whether there is a solution for cross file system moves/renames or whether we have to create temporary output only as subdir of the output path (as done by many other Nutch tools).

**Comment by sebastian-nagel** [comment]
Ok, "it's not possible to run `hdfs dfs -mv` crossing different file systems" [[1](http://stackoverflow.com/questions/34512596/how-does-hdfs-mv-command-work)]. The only solution would be to keep all temporary output which is then moved to the final destination on the file system of the final output.

**Comment by chrismattmann** [comment]
@sebastian-nagel is this ready to commit?

**Comment by sebastian-nagel** [comment]
Almost ready, in my last commit 461fde3 I made a quick fix which needs to be reviewed and cleaned up. I'll do this today. The code was in production a couple of times (crawled over 100 million pages). I'll also double check the modifications in tools which haven't been tested in production (linkdb and indexer). Thanks!

**Comment by sebastian-nagel** [comment]
Ok, ready now from my side.

**Pull request merged**
