### PR TITLE
NUTCH-2263 Support for mingram and maxgram at Unigram Cosine Similarity Model

### PR DESCRIPTION
**Pull request by kamaci**
mingram and maxgram support for Unigram Cosine Similarity Model is provided.

### CODE REVIEW

**Comment by chrismattmann** [comment]
great work @kamaci ! nice!

**Comment by lewismc** [comment]
Tests? Would be grand

On Wednesday, May 18, 2016, Chris Mattmann <notifications@github.com> wrote:

> great work @kamaci <https://github.com/kamaci> ! nice!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/nutch/pull/114#issuecomment-220219317>
>


-- 
*Lewis*

**Comment by kamaci** [comment]
@lewismc is there any existing test base for previous developments? I couldn't see.

**Comment by lewismc** [comment]
I don't think so no, but it would be good to create one either in junit ot
testng

On Thursday, May 19, 2016, Furkan KAMACI <notifications@github.com> wrote:

> @lewismc <https://github.com/lewismc> is there any existing test base for
> previous developments? I couldn't see.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/nutch/pull/114#issuecomment-220353526>
>


-- 
*Lewis*

**Comment by sujen1412** [comment]
A useful to have feature.
And yes a unit test would be great!

Thanks!

**Comment by kamaci** [comment]
This is based on an existence implementation so you can merge this PR and I can create a ticket for test or I can add test implementation to this PR?

**Comment by chrismattmann** [comment]
+1 to commit this, and add tests separately.

**Comment by lewismc** [comment]
ACK +1 from me

**Comment by lewismc** [comment]
@kamaci  can you please squash your commits?

**Comment by kamaci** [comment]
@lewismc I've reset the head. It should be fine now.

**Pull request merged**
