### PR TITLE
NUTCH-1712 Injector to use MultipleInputs (new MR API)

### PR DESCRIPTION
**Pull request by sebastian-nagel**
Tested inject in combination with other CrawlDb tools (readdb, updatedb, mergedb): everything seems to work smoothly, although output files are part-00000 or part-r-00000 (for old resp. new MapReduce API).

### CODE REVIEW

**Comment by lewismc** [comment]
@sebastian-nagel I pulled the patch and tested it locally. It all looks good to me. As it is a large patch, I've provisionally looked over the code and have no gripes about it :)
I would say +1 to commit as it. Addition of tests is nice as well, these all pass as initially stated by yourself.

**Comment by chrismattmann** [comment]
LGTM

**Comment by lewismc** [comment]
@sebastian-nagel you keen to commit? I am working on an overhaul of the entire MR API upgrading everyting to MRv2 so I don't want to screw your patch up.

**Comment by sebastian-nagel** [comment]
Yep, will rebase, resolve conflicts and commit. Looks like I have to commit via git.

**Pull request closed without merging**
