### PR TITLE
NUTCH-2399: Support multivalue fields.

### PR DESCRIPTION
**Pull request by pipldev**
Currently, if there is a NutchField with multiple values, only the first value is indexed (because this is what doc.getFieldValue returns). This fix checks if the NutchField has multiple values, they are added as an array (multivalue) field.

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @pipldev thank you for the patch... can you please open a JIRA issue over at https://issues.apache.org/jira/projects/NUTCH
Additionally, this change would need to be implemented for all indexers not just the elasticsearch indexer.

**Comment by sebastian-nagel** [comment]
indexer-solr already indexes all values. That's why it's mandatory to declare such fields (eg. anchors) in the [schema.xml](https://github.com/apache/nutch/blob/master/conf/schema.xml#L385) as `multiValued="true"`. But yes, it's a good idea to check the remaining indexers as well.

**Comment by pipldev** [comment]
Opened a JIRA issue: https://issues.apache.org/jira/browse/NUTCH-2399.
I don't think I can test the other indexers, as I am not familiar with them and don't have them installed, but seeing as indexer-solr already implements it, it seems like this patch can go forward independently.

**Comment by thilohaas** [comment]
Also submitted a patch for `indexer-elastic-rest` https://github.com/apache/nutch/pull/203

**Comment by jorgelbg** [comment]
This PR contains also the commits for #219 (NUTCH 2415) going to extract the patch to `indexer-elastic` into a separated PR and close this one.

**Comment by pipldev** [comment]
Oops, sorry for that. Not sure how it happened.
Only the a614dd4 commit should be here.

**Comment by jorgelbg** [comment]
@pipldev Don't worry, I'll just open a new PR with your changes. Thanks for the contribution, this was a good catch!

**Pull request closed without merging**
