### PR TITLE
NUTH-2329 Update Slf4j logging for Java 8 and upgrade miredot plugin version

### PR DESCRIPTION
**Pull request by lewismc**
This issue addresses https://issues.apache.org/jira/browse/NUTCH-2329

### CODE REVIEW

**Comment by lewismc** [comment]
@sujen1412 can you please try this out and let me know how you get on with the Miredot documentation?
You need to download the maven-ant-tasks jar and put it in ./ivy you can then generate the documentation by running ```ant restdocs- lib ivy```
Thanks

**Comment by sujen1412** [comment]
Ack'ed will try it out.

**Comment by sujen1412** [comment]
@lewismc the build throwing errors
```
[artifact:mvn] Downloading: http://repo1.maven.org/maven2/org/apache/mrunit/mrunit/1.1.0/mrunit-1.1.0.jar
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [ERROR] BUILD ERROR
[artifact:mvn] [INFO] ------------------------------------------------------------------------
[artifact:mvn] [INFO] Failed to resolve artifact.
[artifact:mvn] 
[artifact:mvn] Missing:
[artifact:mvn] ----------
[artifact:mvn] 1) org.apache.mrunit:mrunit:jar:1.1.0
[artifact:mvn] 
[artifact:mvn]   Try downloading the file manually from the project website.
[artifact:mvn] 
[artifact:mvn]   Then, install it using the command: 
[artifact:mvn]       mvn install:install-file -DgroupId=org.apache.mrunit -DartifactId=mrunit -Dversion=1.1.0 -Dpackaging=jar -Dfile=/path/to/file
[artifact:mvn] 
[artifact:mvn]   Alternatively, if you host your own repository you can deploy the file there: 
[artifact:mvn]       mvn deploy:deploy-file -DgroupId=org.apache.mrunit -DartifactId=mrunit -Dversion=1.1.0 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[artifact:mvn] 
[artifact:mvn]   Path to dependency: 
[artifact:mvn]   	1) org.apache.nutch:nutch:jar:1.13-SNAPSHOT
[artifact:mvn]   	2) org.apache.mrunit:mrunit:jar:1.1.0
[artifact:mvn] 
[artifact:mvn] ----------
[artifact:mvn] 1 required artifact is missing.
```
The jar is not present here : http://repo1.maven.org/maven2/org/apache/mrunit/mrunit/1.1.0/

**Comment by lewismc** [comment]
Yes it is, it is at http://repo1.maven.org/maven2/org/apache/mrunit/mrunit/1.1.0/mrunit-1.1.0-hadoop2.jar
You need to download it manually then run ```mvn install:install-file -DgroupId=org.apache.mrunit -DartifactId=mrunit -Dversion=1.1.0 -Dpackaging=jar -Dfile=mrunit-1.1.0-hadoop2.jar```
The issue is a bug somewhere in Ant + Maven classifiers. I've experienced this for years but never been able to fix it.

**Comment by sebastian-nagel** [comment]
+1 

... or take the jar fetched by ivy: `$HOME/.ivy2/cache/org.apache.mrunit/mrunit/jars/mrunit-1.1.0-hadoop2.jar`. The maven:classifier is not copied into the pom.xml. Ev. related to [IVY-1528](https://issues.apache.org/jira/browse/IVY-1528) but this would need a very recent version of ivy.

**Pull request merged**
