### PR TITLE
NUTCH-2373 Index writer plugin for hbase implemented

### PR DESCRIPTION
**Pull request by kaidul**
An index writer for HBase like index writer for Solr, ElasticSearch etc. Expected HBase table description and NutchDocument to HBase mapping is read using a _indexer-solr_ alike mapping file and write NutchDocument fields into the table of a HBase server.

TODO: Functionality to send and set kerberos authentication configuration for secure hdfs

### CODE REVIEW

**Comment by kaidul** [comment]
I've used {{HBase-0.98.18-hadoop2}} version and APIs. I was really confused which HBase version should I use? Should I use HBase 1.x ? Please review the changes.

**Comment by kaidul** [comment]
Very frustrating for newcomers like me. Not even a single initial response :( :'(

**Comment by sebastian-nagel** [comment]
Hi @kaidul, sorry about any delays. We are a small projects and a small community and a careful review including a test setup will take its time. I hope to get some hours during this week but cannot promise anything. 

Regarding the HBase version: Gora 0.6.1 uses HBase 0.98.8, to avoid any conflicts (if Hbase is used also for storage via Gora) it's for sure not a bad idea to use the same version. But I do not feel really competent in any questions regarding Gora.

**Comment by kaidul** [comment]
Hi @sebastian-nagel , Really thanks for your response. Always appreciate your effort and sorry for my impatience. Without no initial response, I thought my PR might seem somewhat irrelevant for Nutch. Now I know, this PR is on the queue no matter how many days to wait :)

Yes, Fortunately [my current PR uses hbase `0.98.8-hadoop2`](https://github.com/apache/nutch/pull/184/files#diff-34c6548df1ed381822e7318fa954bfda) (sorry for I mistakenly mentioned `0.98.18` which is not correct), so I think this is the same version with gora 0.6.1.

**Comment by kaidul** [comment]
Hi @sju Thanks for your participation. I've added the `commit()` on `close()` and pushed it.

**Comment by lewismc** [comment]
Hi @kaidul yes I shadow @sebastian-nagel comments, apologies for not getting around to this earlier. It is not because the committers don't care, it may have to do with the fact that not everyone has HBase running... regardless thank you for the patch. I managed to try it out with HBase 0.98.X tonight and I am glad to report that it performed flawlessly.
The only comment I really have is if you could implement [parameterized logging](https://www.slf4j.org/faq.html#logging_performance) for Slf4j logging instances.
Thanks again, if you are able to address the logging issue then I would more than happily commit this to master branch.

**Comment by kaidul** [comment]
Hi @lewismc Thanks for your effort to test my patch and I am very glad that everything worked perfectly and the PR is more likely to be merged :D I've added parameterized logging where possible and pushed the changes. However, [here](https://github.com/apache/nutch/pull/184/files#diff-ed9e59402a5d1e6a0f39361b2429e580R97) and [here](https://github.com/apache/nutch/pull/184/files#diff-ed9e59402a5d1e6a0f39361b2429e580R91), the log-messages need to be created to throw `RuntimeException` no matter log is enabled or not. So I used `String.format` here.

Please let me know what you're thinking :)

**Comment by lewismc** [comment]
Thank you @kaidul

**Comment by kaidul** [comment]
You're welcome @lewismc  I really love this project and hope I will be active in this community :)

**Pull request merged**
