### PR TITLE
NUTCH-2972 Javadoc build fails using JDK 17

### PR DESCRIPTION
**Pull request by sebastian-nagel**
- fix Javadoc issues when building with JDK 17
- note: the remaining 100 warnings are all about missing Javadocs for methods and variables

### CODE REVIEW

**Comment by lewismc** [comment]
+1

**Review by lewismc — APPROVED** [review]
+1

**Comment by lewismc** [comment]
We should upgrade the entire codebase to JDK 17.

**Comment by sebastian-nagel** [comment]
> We should upgrade the entire codebase to JDK 17.

Yes. I've opened NUTCH-2987 to track the upgrade to JDK 17.

**Pull request merged**
