### PR TITLE
NUTCH-2891 Upgrade to Tika 2.1.0

### PR DESCRIPTION
**Pull request by sebastian-nagel**
- upgrade Nutch core and the plugins parse-tika and language-identifier
- parse-tika uses on "tika-parsers-standard-package" (no extended and scientific parsers)
- the language-identifier is now based on [Tika's wrapper around Optimaize](https://tika.apache.org/2.1.0/api/org/apache/tika/langdetect/optimaize/OptimaizeLangDetector.html) (overlaps with / obsoletes NUTCH-2449)
- tika-config.xml
  - disable Tesseract OCR
  - add work-around for TIKA-3551

I'll continue testing during the next days.

### CODE REVIEW

**Review by lewismc — COMMENTED** [review]
How extensive has your testing been on this patch @sebastian-nagel ?
I've been running it for quite a while and not experienced any significant issues yet.

**Comment by sebastian-nagel** [comment]
Hi @lewismc, in addition to running local tests on just a few documents
- a comparison of Tika parse results for an equivalent upgrade (/Digitalpebble/storm-crawler#920) showed that any custom extractors need to review metadata names. But the consolidation of Tika metadata names/keys is for sure an improvement for the long term.
- just upgraded the [Common Crawl Nutch fork](/commoncrawl/nutch) and now running a crawl (several 100 million pages) with parse-tika enabled. I'll look for suspicious exceptions in the log files and will report tomorrow.

**Comment by sebastian-nagel** [comment]
Ok, the test crawl was successful. The only dubious errors which need a look at are NoClassDefFoundError parsing files of MIME type `application/x-7z-compressed`. E.g. reproducible by parsing one of the Tika test documents:
```
bin/nutch parsechecker -Dplugin.includes='protocol-file|parse-tika' file:/path/to/tika/repo/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-pkg-module/src/test/resources/test-documents/test-documents.7z
```
Fixed by removing common-codec and commons-compress from the exclusions. Although we have the same versions in core and parse-tika dependencies. Obviously an issue with the plugin and core/parent class loaders.

**Comment by lewismc** [comment]
Hi @sebastian-nagel I didn't encounter `NoClassDefFoundError` because I am not using that parser.

**Pull request merged**
