### PR TITLE
NUTCH-2903 indexer-elastic: allow to connect to Elastic server via HTTPS

### PR DESCRIPTION
**Pull request by sebastian-nagel**

### CODE REVIEW

**Comment by lewismc** [comment]
+1 @sebastian-nagel tested on ES 7.13 to match the plugin High Level REST Client dependency version.
I will note here that the High Level REST Client was deprecated in ES 7.15.0 in favor of the [Java API Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html).

**Comment by sebastian-nagel** [comment]
Thanks, @lewismc! Opened [NUTCH-2927](https://issues.apache.org/jira/browse/NUTCH-2927) to address the upgrade to the Java API client.

**Comment by staminna** [comment]
Does it mean the last version supported for Elasticsearch is 7.13.0? I am going crazy trying to get it to work with 8.6.2

**Comment by sebastian-nagel** [comment]
> Does it mean the last version supported for Elasticsearch is 7.13.0? I am going crazy trying to get it to work with 8.6.2

I'd expect that also later version of 7.x work. Otherwise -- we have to rewrite the indexer-elastic plugin to use the Java API client (see [NUTCH-2927](https://issues.apache.org/jira/browse/NUTCH-2927)) or otherwise remove it due to the incompatible license (NUTCH-2960). Help in implementing NUTCH-2927 is very welcome!

**Pull request merged**
