### PR TITLE
NUTCH-2492: Add more configuration parameters to crawl script

### PR DESCRIPTION
**Pull request by mfeltscher**
Made the following configuration options configurable using command arguments:
- numSlaves
- numTasks
- sizeFetchlist
- timeLimitFetch
- numThreads

I also refactored the usage output in order to make it better readable.

### CODE REVIEW

**Comment by lewismc** [comment]
I really like this.
+1
Anyone else?

**Comment by sebastian-nagel** [comment]
+1 to commit. Looks good, nice extension of the command-line help. Thanks!

**Comment by mfeltscher** [comment]
Thanks!
Wanna merge this? :)

**Comment by mfeltscher** [comment]
Thx @lewismc !

**Pull request merged**
