### PR TITLE
fix for Nutch 1973 by sujen1412

### PR DESCRIPTION
**Pull request by sujen1412**
API calls documented at - https://wiki.apache.org/nutch/Nutch_1.X_RESTAPI.
This pull request includes Index, Generate, Fetch, Parse, Update, InvertLinks, Dedup and Readdb jobs.

### CODE REVIEW

**Comment by lewismc** [comment]
Can you please take a look at the formatting style for Nutch code ?


On Tuesday, March 31, 2015, Sujen Shah <notifications@github.com> wrote:

> API calls documented at - https://wiki.apache.org/nutch/Nutch_1.X_RESTAPI.
> This pull request includes Index, Generate, Fetch, Parse, Update,
> InvertLinks, Dedup and Readdb jobs.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/apache/nutch/pull/16
> Commit Summary
>
>    - Created NutchSever.java
>    - Added cmd line option to start NutchServer on user specified port
>    - Added JobInfo Response object
>    - Added Configuration end point
>    - Update ivy.xml
>    - Request response objects for Configuration support
>    - Merge branch 'NUTCH-1931' of https://github.com/sujen1412/nutch into
>    NUTCH-1931
>    - APache CXF dependency
>    - Added jaxrs dependency
>    - Removed custom providers
>    - Added JobResource
>    - Added AbstractResource
>    - Added JobManager
>    - Added http-jetty dependency
>    - Added "server" option to start NutchServer
>    - Renaming command to startserver
>    - Added Apache license
>    - Added Apache license
>    - Added Apache license
>    - Added Apache license
>    - Added Apache license
>    - Renamed command to start NutchServer in bin/nutch
>    - Start on custom port via -port option
>    - Added command line option -help
>    - Created Nutch tool and implemented in Injector
>    - Instantiated JobManager object
>    - Added new metadata from REST service
>    - Job Enpoint and supporting classes
>    - Changed arguments to Map<String, String> for tool
>    - Classes for the job endpoint
>    - Changed the result arg to Map<String, Object>
>    - Added DbResource for running readdb
>    - Added support for dump, url options in readdb
>    - Corrected the -dir | segments option
>    - Added License info
>    - Added constructor
>    - Removed commented lines
>    - Corrected indentation
>    - Corrected constructor call
>    - Corrected required number of args
>    - Corrected args for dir and <seg> <seg>
>
> File Changes
>
>    - *M* ivy/ivy.xml
>    <https://github.com/apache/nutch/pull/16/files#diff-0> (8)
>    - *M* src/bin/nutch
>    <https://github.com/apache/nutch/pull/16/files#diff-1> (3)
>    - *M* src/java/org/apache/nutch/crawl/CrawlDb.java
>    <https://github.com/apache/nutch/pull/16/files#diff-2> (61)
>    - *M* src/java/org/apache/nutch/crawl/CrawlDbReader.java
>    <https://github.com/apache/nutch/pull/16/files#diff-3> (256)
>    - *M* src/java/org/apache/nutch/crawl/DeduplicationJob.java
>    <https://github.com/apache/nutch/pull/16/files#diff-4> (19)
>    - *M* src/java/org/apache/nutch/crawl/Generator.java
>    <https://github.com/apache/nutch/pull/16/files#diff-5> (64)
>    - *M* src/java/org/apache/nutch/crawl/Injector.java
>    <https://github.com/apache/nutch/pull/16/files#diff-6> (24)
>    - *M* src/java/org/apache/nutch/crawl/LinkDb.java
>    <https://github.com/apache/nutch/pull/16/files#diff-7> (54)
>    - *M* src/java/org/apache/nutch/fetcher/Fetcher.java
>    <https://github.com/apache/nutch/pull/16/files#diff-8> (41)
>    - *M* src/java/org/apache/nutch/metadata/Nutch.java
>    <https://github.com/apache/nutch/pull/16/files#diff-9> (66)
>    - *M* src/java/org/apache/nutch/parse/ParseSegment.java
>    <https://github.com/apache/nutch/pull/16/files#diff-10> (25)
>    - *A* src/java/org/apache/nutch/service/ConfManager.java
>    <https://github.com/apache/nutch/pull/16/files#diff-11> (39)
>    - *A* src/java/org/apache/nutch/service/JobManager.java
>    <https://github.com/apache/nutch/pull/16/files#diff-12> (46)
>    - *A* src/java/org/apache/nutch/service/NutchServer.java
>    <https://github.com/apache/nutch/pull/16/files#diff-13> (177)
>    - *A* src/java/org/apache/nutch/service/impl/ConfManagerImpl.java
>    <https://github.com/apache/nutch/pull/16/files#diff-14> (132)
>    - *A* src/java/org/apache/nutch/service/impl/JobFactory.java
>    <https://github.com/apache/nutch/pull/16/files#diff-15> (73)
>    - *A* src/java/org/apache/nutch/service/impl/JobManagerImpl.java
>    <https://github.com/apache/nutch/pull/16/files#diff-16> (95)
>    - *A* src/java/org/apache/nutch/service/impl/JobWorker.java
>    <https://github.com/apache/nutch/pull/16/files#diff-17> (98)
>    - *A*
>    src/java/org/apache/nutch/service/impl/NutchServerPoolExecutor.java
>    <https://github.com/apache/nutch/pull/16/files#diff-18> (131)
>    - *A* src/java/org/apache/nutch/service/model/request/DbQuery.java
>    <https://github.com/apache/nutch/pull/16/files#diff-19> (48)
>    - *A* src/java/org/apache/nutch/service/model/request/JobConfig.java
>    <https://github.com/apache/nutch/pull/16/files#diff-20> (71)
>    - *A* src/java/org/apache/nutch/service/model/request/NutchConfig.java
>    <https://github.com/apache/nutch/pull/16/files#diff-21> (51)
>    - *A* src/java/org/apache/nutch/service/model/response/JobInfo.java
>    <https://github.com/apache/nutch/pull/16/files#diff-22> (102)
>    - *A* src/java/org/apache/nutch/service/resources/AbstractResource.java
>    <https://github.com/apache/nutch/pull/16/files#diff-23> (43)
>    - *A* src/java/org/apache/nutch/service/resources/ConfigResource.java
>    <https://github.com/apache/nutch/pull/16/files#diff-24> (79)
>    - *A* src/java/org/apache/nutch/service/resources/DbResource.java
>    <https://github.com/apache/nutch/pull/16/files#diff-25> (101)
>    - *A* src/java/org/apache/nutch/service/resources/JobResource.java
>    <https://github.com/apache/nutch/pull/16/files#diff-26> (72)
>    - *A* src/java/org/apache/nutch/util/NutchTool.java
>    <https://github.com/apache/nutch/pull/16/files#diff-27> (92)
>
> Patch Links:
>
>    - https://github.com/apache/nutch/pull/16.patch
>    - https://github.com/apache/nutch/pull/16.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/nutch/pull/16>.
>


-- 
*Lewis*

**Comment by sujen1412** [comment]
Shall I use this - http://svn.apache.org/repos/asf/nutch/branches/2.x/eclipse-codeformat.xml ?

**Comment by lewismc** [comment]
Please thank you very much Sujen. Great work this is going very well.
I'll test out ASAP and make best efforts to drive towards a commit on the
Backport f the REST API. This is grand.

On Tuesday, March 31, 2015, Sujen Shah <notifications@github.com> wrote:

> Shall I use this -
> http://svn.apache.org/repos/asf/nutch/branches/2.x/eclipse-codeformat.xml
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/nutch/pull/16#issuecomment-88311455>.
>


-- 
*Lewis*

**Comment by sujen1412** [comment]
I am just finishing writing a tutorial on how to run the jobs, on the wiki. The current documentation just gives an example with placeholder arguments. 
Will post link as soon as I am done.

**Comment by lewismc** [comment]
Ack good job

On Tuesday, March 31, 2015, Sujen Shah <notifications@github.com> wrote:

> I am just finishing writing a tutorial on how to run the jobs, on the
> wiki. The current documentation just gives an example with placeholder
> arguments.
> Will post link as soon as I am done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apache/nutch/pull/16#issuecomment-88312428>.
>


-- 
*Lewis*

**Comment by sujen1412** [comment]
Here is the link - https://wiki.apache.org/nutch/Nutch_1.X_RESTAPI/RunningJobsTutorial

**Comment by sujen1412** [comment]
Corrected formatting to conform with Nutch code formatting style

**Comment by chrismattmann** [comment]
Hey Sujen, this patch doesn't apply cleanly to Nutch there are merge conflicts. Can you please correct them and open up a new PR?

**Comment by sujen1412** [comment]
Yes will do it.

**Comment by chrismattmann** [comment]
ping @sujen1412 can you please update the PR?

**Comment by sujen1412** [comment]
Yes, apologies for the delay will do it by today evening.

**Comment by sujen1412** [comment]
Updated, and resolved merge conflicts.

**Comment by chrismattmann** [comment]
@sujen1412 this doesn't apply cleanly can you see my comments on the JIRA?

**Comment by sujen1412** [comment]
Yes, saw them. I'm working on cleaning the patch.

**Comment by chrismattmann** [comment]
Thanks @sujen1412 let me know when it's ready

**Comment by chrismattmann** [comment]
@sujen1412 did you complete this?

**Comment by chrismattmann** [comment]
So I pulled out the missing files:

[usc-secure-wireless-061-034:~/tmp/nutch-1.10-trunk] mattmann% svn commit -m "Remainder of fix for NUTCH-1973: Job Administration end point for the REST service contributed by Sujen Shah <sujen1412@gmail.com>"
Adding         src/java/org/apache/nutch/service/model/request/JobConfig.java
Adding         src/java/org/apache/nutch/util/NutchTool.java
Transmitting file data ..
Committed revision 1675249.
[usc-secure-wireless-061-034:~/tmp/nutch-1.10-trunk] mattmann%

**Pull request closed without merging**
