### PR TITLE
NUTCH-2857 Upgrade from JDK1.8 --> JDK11

### PR DESCRIPTION
**Pull request by lewismc**
This issue proposes to fix https://issues.apache.org/jira/browse/NUTCH-2857
This results in the following local failures when testing plugins
```
Testsuite: org.apache.nutch.protocol.http.TestProtocolHttp
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.336 sec
...
2021-03-12 19:01:53,905 ERROR mortbay.log (Slf4jLog.java:warn(87)) - /basic-http.jsp
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at org.apache.jasper.compiler.JspRuntimeContext.<init>(JspRuntimeContext.java:94)
	at org.apache.jasper.servlet.JspServlet.init(JspServlet.java:100)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:339)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```
The same JDK issues are present in the following tests as well
```
Testsuite: org.apache.nutch.protocol.httpclient.TestProtocolHttpClient
Tests run: 7, Failures: 7, Errors: 0, Skipped: 0, Time elapsed: 1.644 sec
```
and
```
Testsuite: org.apache.nutch.protocol.okhttp.TestProtocolOkHttp
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.827 sec
```
Additionally, I think we might want to address deprecation in the Nutch API. For example, when I execute a build, I see **59** javac deprecation notices in my build log. Maybe we could address that in a separate issue...

Thanks for anyone who can also review this patch.

### CODE REVIEW

**Comment by sebastian-nagel** [comment]
Hi Lewis, the issues with the Jetty version and JDK >8 are tracked in NUTCH-2596 - some work is already done.

+ 1 to deprecate the Nutch API and the server which depends on it, or at least, to seriously discuss this option.

**Comment by lewismc** [comment]
Perfect @sebastian-nagel I missed this work when you and @balashashanka discussed it previously.
I'll go back and check it all out. Thanks

**Comment by lewismc** [comment]
Most recent commit ensures there are no merge conflicts [post-NUTCH-2596](https://github.com/apache/nutch/pull/574)
Some trivial Javadoc updates were required. I am actively testing this patch. Feedback welcome.

**Review by sebastian-nagel — APPROVED** [review]
+1 compiles, unit tests pass and Nutch web API and server are running. Tested using JDK 11.

**Pull request merged**
