### PR TITLE
fix for NUTCH-1944 Index HTML raw content contributed by meabed

### PR DESCRIPTION
**Pull request by Meabed**
Index-html Plugin for apache nutch 2.x
Index HTML content of the pages in Apache Nutch 2.x 
-- Please refer to the README in the plugin folder, or here https://github.com/Meabed/nutch2-index-html

### CODE REVIEW

**Comment by lewismc** [comment]
Hi @Meabed I look at the patch, It looks like it does not include the content for the Solr schema.xml.
Can you possibly modify the PR to include this?
Thank you. I will work to get this in to the codebase. Thanks

**Comment by chrismattmann** [comment]
Hi @Meabed ping, do you have a chance to add the Solr schema.xml mods? Thanks!! Looking forward to this.

**Comment by Meabed** [comment]
Yes updated :), please have a look at it.
Thanks

**Comment by chrismattmann** [comment]
thanks @Meabed I went ahead and committed this! Thanks!

**Pull request closed without merging**
