### PR TITLE
fix for NUTCH-2132 contributed by r0ann3l

### PR DESCRIPTION
**Pull request by r0ann3l**
Added new properties and fixed a ClassNotFoundException.

### CODE REVIEW

**Comment by jnioche** [comment]
What about squashing your commits and providing at least some explanations as to what you are trying to achieve?

**Comment by lewismc** [comment]
@r0ann3l can you please open a ticket over on Jira? https://issues.apache.org/jira/browse/NUTCH, this will help us track it and assign it to a Nutch version.

**Comment by jnioche** [comment]
[https://issues.apache.org/jira/browse/NUTCH-2333]?

**Comment by lewismc** [comment]
@r0ann3l can you confirm please?

**Comment by r0ann3l** [comment]
@lewismc and @jnioche this pull request isn't for NUTCH-2333. It's for NUTCH-2132. This code includes new properties to establish the connection with a RabbitMQ server, such as port, virtual host, user, password. Also includes a queue.name and a queue.durable properties. Besides, I include the reference to amqp-client library in plugin.xml file for publish-rabbitmq plugin.

**Pull request merged**
